# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: fetch_build_push_image

on:
  workflow_call:
    inputs:
      source_repository:
        description: 'Repository to fetch'
        required: true
        type: string
      source_branch:
        description: 'Branch to fetch'
        required: false
        default: 'main'
        type: string
      source_dockerfile:
        description: 'Dockerfile to use'
        required: false
        default: 'Dockerfile'
        type: string
      source_build_context:
        description: 'Build context to use'
        required: false
        default: '.'
        type: string
      source_build_args:
        description: 'List of build-time variables'
        required: false
        default: ''
        type: string
      target_architecture:
        description: 'Architecture to fetch'
        required: false
        default: 'linux/amd64'
        type: string
      target_image:
        description: 'Full path, name and tag of the target image'
        required: true
        type: string
      target_registry:
        description: 'Registry to push the image to'
        required: false
        default: ''
        type: string
      target_registry_username:
        description: 'Username for the registry'
        required: false
        default: ''
        type: string

    secrets:
      target_registry_password:
        description: 'Password for the registry'
        required: false

jobs:
  build:
    uses: ./.github/workflows/_fetch_build_push_docker_image.yml
    with:
      source_repository: ${{ inputs.source_repository }}
      source_branch: ${{ inputs.source_branch }}
      source_dockerfile: ${{ inputs.source_dockerfile }}
      source_build_context: ${{ inputs.source_build_context }}
      source_build_args: ${{ inputs.source_build_args }}
      target_architecture: ${{ inputs.target_architecture }}
      target_image: ${{ inputs.target_image }}
      target_registry: ${{ inputs.target_registry }}
      target_registry_username: ${{ inputs.target_registry_username }}
    secrets:
      target_registry_password: ${{ secrets.target_registry_password }}
