# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: gateway

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-gateway-jumper:
    uses: ./.github/workflows/_fetch_build_push_image.yml
    with:
      source_repository: 'telekom/gateway-jumper'
      source_dockerfile: 'Dockerfile.multi-stage'
      target_image: 'ghcr.io/${{ github.repository_owner }}/o28m/gateway-jumper'
      target_architecture: 'linux/amd64, linux/arm64'
      target_registry: 'ghcr.io'
      target_registry_username: ${{ github.actor }}
    secrets:
      target_registry_password: ${{ secrets.GITHUB_TOKEN }}

  build-gateway-issuer-service:
    uses: ./.github/workflows/_fetch_build_push_image.yml
    with:
      source_repository: 'telekom/gateway-issuer-service-go'
      source_dockerfile: 'Dockerfile.multi-stage'
      target_image: 'ghcr.io/${{ github.repository_owner }}/o28m/gateway-issuer-service-go'
      target_architecture: 'linux/amd64, linux/arm64'
      target_registry: 'ghcr.io'
      target_registry_username: ${{ github.actor }}
    secrets:
      target_registry_password: ${{ secrets.GITHUB_TOKEN }}

  build-gateway-kong:
    uses: ./.github/workflows/_fetch_build_push_image.yml
    with:
      source_repository: 'telekom/gateway-kong-image'
      source_branch: 'main'
      source_build_args: |
        KONG_VERSION=2.8.3
        PLUGIN_VERSION=1.3.0-1
      target_image: 'ghcr.io/${{ github.repository_owner }}/o28m/gateway-kong'
      target_architecture: 'linux/amd64, linux/arm64'
      target_registry: 'ghcr.io'
      target_registry_username: ${{ github.actor }}
    secrets:
      target_registry_password: ${{ secrets.GITHUB_TOKEN }}
